name: "Build & Test"

on:
  push:
    branches: ["main","rfc/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Update APT Cache
        run: sudo apt-get update
      - name: Install (APT)
        run: sudo apt-get install asciidoctor
      - name: Install (B2)
        run: |
          set -e
          pushd ..
          wget "https://github.com/bfgroup/b2/archive/main.zip" -O b2.zip
          unzip b2.zip
          cd b2-main
          CXX= ./bootstrap.sh
          CXX= sudo ./b2 install b2-install-layout=portable --prefix=/usr/bin
          popd
          echo "using asciidoctor ;" > project-config.jam
      - name: Build (Web)
        run: b2 --debug-configuration -d+2 pub
      - name: Test (Validate)
        run: b2 --debug-configuration -d+2 validate
